---
- name: git config name setting
  git_config:
    name: user.name
    scope: global
    value: "{{ git_user }}"

- name: git config email setting
  git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"
